### ISSUE TITLE
请教个问题，这个项目为了解决啥痛点，使用这个项目会带来啥好处

### ISSUE THREAD

**Issue by haicc-wang** [shiyindaxiaojie/eden-architect#159]
看起来，是不是，多个最佳业界解决的high-level封装？

**Comment by haicc-wang** [comment]
xxx

**Comment by kamjin1996** [comment]
666，就是一个个人用的脚手架，还是自己封装的用的习惯，这个很不习惯

**Comment by shiyindaxiaojie** [comment]
这个项目初期是给研发团队搭建脚手架，慢慢迭代起来的，设计原则以通用解决方案为主，大概考虑的几个点： 
1. 复用
2. 解决方案
3. 可拆、可组装

实际上可以理解为一个参考案例，可以这么做：
1. 直接引用到项目中，开箱即用，节省时间。
2. 不使用这个项目，但可以参考每个 Spring Boot Starter 的做法，单独复制代码片段，拆出去使用。
